// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA54d6lOzLs7jr-jgs1PHCGNcb7jmXesLM',
    appId: '1:260268431903:web:153cc6744395c99b6b532a',
    messagingSenderId: '260268431903',
    projectId: 'flutter-tasklist-project',
    authDomain: 'flutter-tasklist-project.firebaseapp.com',
    storageBucket: 'flutter-tasklist-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFNjn2-__h4F6eq2ll2RlM9bmtOQj7Jg',
    appId: '1:260268431903:android:4e902f59949f3f8e6b532a',
    messagingSenderId: '260268431903',
    projectId: 'flutter-tasklist-project',
    storageBucket: 'flutter-tasklist-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapH9LFWtNSKm92XOW5SABVuuYp80CyN0',
    appId: '1:260268431903:ios:bcd4826b769f76a16b532a',
    messagingSenderId: '260268431903',
    projectId: 'flutter-tasklist-project',
    storageBucket: 'flutter-tasklist-project.appspot.com',
    iosBundleId: 'ryan.shelldon.todoListProject',
  );
}
